#!/usr/bin/env python3
"""
Migration: Fix automated_search_history table structure for PostgreSQL

This script ensures:
1. Table exists with correct SERIAL PRIMARY KEY
2. pickup_date column exists
3. supplier_data column exists (JSONB for PostgreSQL)
"""

import os
import sys
import psycopg2
from psycopg2 import sql

def get_db_connection():
    """Get PostgreSQL connection from environment variables"""
    database_url = os.environ.get('DATABASE_URL')
    
    if not database_url:
        print("❌ DATABASE_URL environment variable not set")
        sys.exit(1)
    
    try:
        conn = psycopg2.connect(database_url)
        print(f"✅ Connected to PostgreSQL database")
        return conn
    except Exception as e:
        print(f"❌ Failed to connect to database: {e}")
        sys.exit(1)

def check_table_exists(conn, table_name):
    """Check if table exists"""
    with conn.cursor() as cur:
        cur.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_name = %s
            )
        """, (table_name,))
        return cur.fetchone()[0]

def check_column_exists(conn, table_name, column_name):
    """Check if column exists in table"""
    with conn.cursor() as cur:
        cur.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.columns 
                WHERE table_name = %s AND column_name = %s
            )
        """, (table_name, column_name))
        return cur.fetchone()[0]

def create_automated_search_history_table(conn):
    """Create or update automated_search_history table"""
    
    print("\n📋 Checking automated_search_history table...")
    
    table_exists = check_table_exists(conn, 'automated_search_history')
    
    if not table_exists:
        print("⚠️  Table does not exist. Creating...")
        with conn.cursor() as cur:
            cur.execute("""
                CREATE TABLE automated_search_history (
                    id SERIAL PRIMARY KEY,
                    location TEXT NOT NULL,
                    search_type TEXT NOT NULL,
                    search_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    month_key TEXT NOT NULL,
                    prices_data JSONB NOT NULL,
                    dias TEXT NOT NULL,
                    price_count INTEGER DEFAULT 0,
                    user_email TEXT,
                    supplier_data JSONB,
                    pickup_date DATE,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
            """)
            conn.commit()
            print("✅ Table created successfully")
        
        # Create index
        with conn.cursor() as cur:
            cur.execute("""
                CREATE INDEX IF NOT EXISTS idx_automated_search_month 
                ON automated_search_history(month_key, search_type, search_date DESC)
            """)
            conn.commit()
            print("✅ Index created")
    else:
        print("✅ Table exists")
        
        # Check and add missing columns
        columns_to_add = [
            ('supplier_data', 'JSONB', 'Supplier data for visual cards'),
            ('pickup_date', 'DATE', 'Pickup date of search')
        ]
        
        for column_name, column_type, description in columns_to_add:
            if not check_column_exists(conn, 'automated_search_history', column_name):
                print(f"⚠️  Column '{column_name}' missing. Adding...")
                with conn.cursor() as cur:
                    cur.execute(f"""
                        ALTER TABLE automated_search_history 
                        ADD COLUMN {column_name} {column_type}
                    """)
                    conn.commit()
                    print(f"✅ Added column '{column_name}' ({description})")
            else:
                print(f"✅ Column '{column_name}' exists")
        
        # Check if id column is SERIAL
        with conn.cursor() as cur:
            cur.execute("""
                SELECT column_default 
                FROM information_schema.columns 
                WHERE table_name = 'automated_search_history' 
                AND column_name = 'id'
            """)
            result = cur.fetchone()
            if result and 'nextval' in str(result[0]):
                print("✅ ID column is SERIAL (auto-increment)")
            else:
                print("⚠️  ID column is NOT SERIAL. Manual fix required!")
                print("   Run: ALTER TABLE automated_search_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;")

def main():
    print("=" * 60)
    print("🔧 Fix automated_search_history Table Structure")
    print("=" * 60)
    
    conn = get_db_connection()
    
    try:
        create_automated_search_history_table(conn)
        
        print("\n" + "=" * 60)
        print("✅ Migration completed successfully!")
        print("=" * 60)
        
    except Exception as e:
        print(f"\n❌ Migration failed: {e}")
        import traceback
        traceback.print_exc()
        conn.rollback()
        sys.exit(1)
    finally:
        conn.close()

if __name__ == "__main__":
    main()
